PUT http://localhost:3001/api/blogs/3
Content-Type: application/json

{
  "likes": 12
}

###

PUT http://localhost:3001/api/users/Testing
Content-Type: application/json

{
  "username": "don@donjohn.com"
}