PUT http://localhost:3001/api/blogs/4
Content-Type: application/json

{
  "likes": 5
}

###

PUT http://localhost:3001/api/users/Testing
Content-Type: application/json

{
  "username": "don@donjohn.com"
}